### ISSUE TITLE
When %FACTION% is in the Superbar config it doesnt load up

### ISSUE THREAD

**Issue by shavindanagapen** [JackMD/superBAR#2]

**Comment by Ifera** [comment]
Which faction plugin are you using?

**Comment by Ifera** [comment]
By far only [Faction pro](https://poggit.pmmp.io/p/FactionsPro/1.3.11-9) is supported. Try using that and see if the problem still occurs.

**Comment by shavindanagapen** [comment]
I use factions pro.

**Comment by Ifera** [comment]
Everything is working as supposed to. Read [this](https://github.com/JackMD/superBAR/blob/a035dab1054be2fb63678ab9cb1b8f2b763f0ccb/resources/config.yml#L68) line of config.yml.
```68 #This will be displayed (in %FACTION%) if the player does not have a faction```
```69 no-faction: "NoFaction"```
It means the player is not in a faction and thus the result `NoFaction`.
